### ISSUE TITLE
const [datatype] vs. #define

### ISSUE THREAD

**Issue by ericklein** [ericklein/realtime_co2#19]
ericklein/airquality/#83

**Comment by disquisitioner** [comment]
Generally const int is better but there isn't an easy way to override the setting later as the compiler honors your declaration that the value is indeed constant.

We have a number of parameters in config.h that I want to override in my secrets.h, so I #undef them there and then redefine them with a new #define.  That lets me change, e.g. debug and regular reporting intervals, MQTT topics, etc. The alternative is to edit them in config.h directly, but given that file is in the repo and secrets.h isn't, I'd either end up merging my custom values back into the repo or I'd have to revert my changes to config.h.

Using the #undef and #define pattern in secrets.h  means I can leave config.h alone and still easily compile and run code updated from main without a bunch of file reversion or swapping around. 

I can see using const int for things like the size of our non-volatile storage, string defines for the names of the days of the week, etc.  For things that are configuration settings (like display rotation) it's easier if they can be #defines in config.h so they can then be #undef/#define redefined seamlessly in secrets.h.
